### ISSUE TITLE
The lib cannot found it.

### ISSUE THREAD

**Issue by yorcan** [kripton/lcdproc-networkmanager#1]
hi,when i make this project,the complier show the libnm development package not found.
thanks.

**Comment by kripton** [comment]
You need to have the header files of libnm installed. Depending on the OS and distribution you are using, the way to install them is different.
If you are on a Debian-based system, try running `sudo apt-get install libnm-dev`

**Comment by yorcan** [comment]
ok,i got,thanks for your reply
